//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookshop.Model
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class ActionInfo
    {
        public ActionInfo()
        {
            this.R_UserInfo_ActionInfo = new HashSet<R_UserInfo_ActionInfo>();
            this.ActionGroup = new HashSet<ActionGroup>();
            this.Role = new HashSet<Role>();
        }
    
        public int ID { get; set; }
        public string ActionInfoName { get; set; }
        public string Url { get; set; }
        public short HttpMethod { get; set; }
        public string Remark { get; set; }
        public short DelFalg { get; set; }
        public System.DateTime SubTime { get; set; }
        public bool IsMenu { get; set; }
        public int R_UserInfo_ActionInfoID { get; set; }
    
    	[JsonIgnore]
        public virtual ICollection<R_UserInfo_ActionInfo> R_UserInfo_ActionInfo { get; set; }
    	[JsonIgnore]
        public virtual ICollection<ActionGroup> ActionGroup { get; set; }
    	[JsonIgnore]
        public virtual ICollection<Role> Role { get; set; }
    }
}
