//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookshop.Model
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Articel_Words
    {
        public int Id { get; set; }
        public string WordPattern { get; set; }
        public bool IsForbid { get; set; }
        public bool IsMod { get; set; }
        public string ReplaceWord { get; set; }
    }
}
