//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookshop.Model
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class BookComment
    {
        public int Id { get; set; }
        public string Msg { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public int BookId { get; set; }
        public Nullable<bool> IsPass { get; set; }
    }
}
