//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookshop.Model
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public Books()
        {
            this.Cart = new HashSet<Cart>();
            this.OrderBook = new HashSet<OrderBook>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public int PublisherId { get; set; }
        public System.DateTime PublishDate { get; set; }
        public string ISBN { get; set; }
        public int WordsCount { get; set; }
        public decimal UnitPrice { get; set; }
        public string ContentDescription { get; set; }
        public string AurhorDescription { get; set; }
        public string EditorComment { get; set; }
        public string TOC { get; set; }
        public int CategoryId { get; set; }
        public int Clicks { get; set; }
    
    	[JsonIgnore]
        public virtual Categories Categories { get; set; }
    	[JsonIgnore]
        public virtual Publishers Publishers { get; set; }
    	[JsonIgnore]
        public virtual ICollection<Cart> Cart { get; set; }
    	[JsonIgnore]
        public virtual ICollection<OrderBook> OrderBook { get; set; }
    }
}
