//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookshop.Model
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.Role = new HashSet<Role>();
        }
    
        public int ID { get; set; }
        public string DepName { get; set; }
        public int RoleID { get; set; }
    
    	[JsonIgnore]
        public virtual ICollection<Role> Role { get; set; }
    }
}
