//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookshop.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class book_shop3Entities : DbContext
    {
        public book_shop3Entities()
            : base("name=book_shop3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ActionGroup> ActionGroup { get; set; }
        public DbSet<ActionInfo> ActionInfo { get; set; }
        public DbSet<Articel_Words> Articel_Words { get; set; }
        public DbSet<BookComment> BookComment { get; set; }
        public DbSet<Books> Books { get; set; }
        public DbSet<Cart> Cart { get; set; }
        public DbSet<Categories> Categories { get; set; }
        public DbSet<CheckEmail> CheckEmail { get; set; }
        public DbSet<Department> Department { get; set; }
        public DbSet<keyWordsRank> keyWordsRank { get; set; }
        public DbSet<OrderBook> OrderBook { get; set; }
        public DbSet<Orders> Orders { get; set; }
        public DbSet<Publishers> Publishers { get; set; }
        public DbSet<R_UserInfo_ActionInfo> R_UserInfo_ActionInfo { get; set; }
        public DbSet<Role> Role { get; set; }
        public DbSet<SearchDetails> SearchDetails { get; set; }
        public DbSet<Settings> Settings { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<SysFun> SysFun { get; set; }
        public DbSet<UserInfo> UserInfo { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<UserStates> UserStates { get; set; }
        public DbSet<VidoFile> VidoFile { get; set; }
        public DbSet<AddressInfo> AddressInfo { get; set; }
    }
}
