//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookshop.Model
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.ActionGroup = new HashSet<ActionGroup>();
            this.ActionInfo = new HashSet<ActionInfo>();
            this.Department = new HashSet<Department>();
            this.UserInfo = new HashSet<UserInfo>();
        }
    
        public int ID { get; set; }
        public string RoleName { get; set; }
        public short DelFlag { get; set; }
        public short RoleType { get; set; }
        public System.DateTime SubTime { get; set; }
        public string Remark { get; set; }
    
    	[JsonIgnore]
        public virtual ICollection<ActionGroup> ActionGroup { get; set; }
    	[JsonIgnore]
        public virtual ICollection<ActionInfo> ActionInfo { get; set; }
    	[JsonIgnore]
        public virtual ICollection<Department> Department { get; set; }
    	[JsonIgnore]
        public virtual ICollection<UserInfo> UserInfo { get; set; }
    }
}
