//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookshop.Model
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class SysFun
    {
        public int NodeId { get; set; }
        public string DisplayName { get; set; }
        public string NodeURL { get; set; }
        public int DisplayOrder { get; set; }
        public int ParentNodeId { get; set; }
    }
}
